"""Write heavy analyses as job files instead of running them inside the application."""

from __future__ import annotations

import shutil
from pathlib import Path

from adit.lang import L

WORKER_FILE = "msd_worker.py"
JOB_FILE = "msd_run.sh"
RESULT_FILE = "msd_vanhove.json"

SECONDS_PER_DISPLACEMENT = 1.0e-7
SECONDS_PER_TAU_FIT = 5.0e-3
BYTES_PER_ATOM_FRAME = 24


def estimate(frames: int, atoms: int, taus: int = 100, displacement: str = "mic") -> dict:
    frames, atoms, taus = max(int(frames), 0), max(int(atoms), 0), max(int(taus), 0)
    displacements = 0.75 * taus * frames * atoms
    images = 27 if displacement == "mic" else 1
    seconds = displacements * SECONDS_PER_DISPLACEMENT * (images / 27) + taus * SECONDS_PER_TAU_FIT
    coords_mb = frames * atoms * BYTES_PER_ATOM_FRAME / 1e6
    return {"frames": frames, "atoms": atoms, "taus": taus, "displacements": int(displacements),
            "seconds": float(seconds), "coordinates_mb": float(coords_mb),
            "note": L("見積もりです (実際には計算していません)。係数は 2026-09-13 に手元で測った値",
                      "an estimate (nothing was computed); the constants were measured on 2026-09-13")}


def is_heavy(frames: int, atoms: int, taus: int = 100, limit_seconds: float = 60.0) -> bool:
    return estimate(frames, atoms, taus)["seconds"] > limit_seconds


def write_job(run_dir: Path | str, *, dt_fs: float, species: str | None = None, taus: int = 100,
              displacement: str = "mic", natoms: int = 0, trajectory: str = "", cell_file: str = "",
              profile=None, spec=None) -> list[Path]:
    """Write the files for a heavy analysis into a run directory and return the written paths. With profile and spec the job script is for a cluster; otherwise it runs locally. Nothing is submitted."""
    out = Path(run_dir).expanduser()
    out.mkdir(parents=True, exist_ok=True)
    worker_src = Path(__file__).resolve().parent / WORKER_FILE
    shutil.copy2(worker_src, out / WORKER_FILE)
    args = [WORKER_FILE, trajectory or "<軌跡のファイル>", f"--dt {dt_fs:g}", f"--taus {taus}",
            f"--displacement {displacement}"]
    if natoms:
        args.append(f"--natoms {natoms}")
    if cell_file:
        args.append(f"--cell {cell_file}")
    if species:
        args.append(f"--species {species}")
    command = "python " + " ".join(args)
    body = [
        "#!/bin/bash",
        L("# ADIT が生成した、重い解析を実行する手順。ADIT は投入しません。人が実行します。",
          "# Generated by ADIT to run the heavy analysis. ADIT does not submit it; a human runs it."),
        L(f"# 走り終わると {RESULT_FILE} ができます。図にするのは adit-analyze <このディレクトリ> です。",
          f"# It writes {RESULT_FILE}; plot it with adit-analyze <this directory>."),
        L("# 要るもの: numpy と scipy だけ (ADIT は要りません)。",
          "# Requirements: numpy and scipy only (ADIT is not needed)."),
        'cd "$(dirname "$0")"',
        command,
        "",
    ]
    text = "\n".join(body)
    if profile is not None and spec is not None:
        from adit.scripts.render import render_submit

        try:
            text = render_submit(spec, profile, command)
        except Exception:
            pass
    path = out / JOB_FILE
    path.write_text(text, encoding="utf-8", newline="\n")
    try:
        path.chmod(0o755)
    except OSError:
        pass
    return [out / WORKER_FILE, path]


def readme_lines(estimate_info: dict) -> list[str]:
    return [
        L(f"  {JOB_FILE}    重い解析 (原子ごとの拡散係数・変位の分布) を実行する手順。見積もり "
          f"{estimate_info['seconds']:.0f} 秒、座標 {estimate_info['coordinates_mb']:.0f} MB",
          f"  {JOB_FILE}    how to run the heavy analysis (per-atom diffusion, displacement distribution); "
          f"estimated {estimate_info['seconds']:.0f} s and {estimate_info['coordinates_mb']:.0f} MB of coordinates"),
        L(f"  {WORKER_FILE}   その本体 (numpy と scipy だけで動きます。ADIT は要りません)",
          f"  {WORKER_FILE}   the worker itself (numpy and scipy only; ADIT is not required)"),
        L(f"  実行すると {RESULT_FILE} ができます。そのあと adit-analyze <このディレクトリ> で図になります。",
          f"  Running it writes {RESULT_FILE}; then adit-analyze <this directory> turns it into figures."),
    ]
