
SOLVENTS: tuple[tuple[tuple[str, ...], bool, bool], ...] = (
    (('1,1,1-trichloroethane',), True, True),
    (('1,1,2-trichloroethane',), True, True),
    (('1,2,4-trimethylbenzene',), True, True),
    (('1,2-dibromoethane',), True, True),
    (('1,2-dichloroethane',), True, True),
    (('1,2-ethanediol',), True, True),
    (('1,4-dioxane', 'dioxane'), True, True),
    (('1-bromo-2-methylpropane',), True, True),
    (('1-bromooctane', 'bromooctane'), True, True),
    (('1-bromopentane',), True, True),
    (('1-bromopropane',), True, True),
    (('1-butanol', 'butanol'), True, True),
    (('1-chlorohexane', 'chlorohexane'), True, True),
    (('1-chloropentane',), True, True),
    (('1-chloropropane',), True, True),
    (('1-decanol', 'decanol'), True, True),
    (('1-fluorooctane',), True, True),
    (('1-heptanol', 'heptanol'), True, True),
    (('1-hexanol', 'hexanol'), True, True),
    (('1-hexene',), True, True),
    (('1-hexyne',), True, True),
    (('1-iodobutane',), True, True),
    (('1-iodohexadecane', 'hexadecyliodide'), True, True),
    (('1-iodopentane',), True, True),
    (('1-iodopropane',), True, True),
    (('1-nitropropane',), True, True),
    (('1-nonanol', 'nonanol'), True, True),
    (('1-octanol', 'octanol'), True, True),
    (('1-pentanol', 'pentanol'), True, True),
    (('1-pentene',), True, True),
    (('1-propanol', 'propanol'), True, True),
    (('2,2,2-trifluoroethanol',), True, True),
    (('2,2,4-trimethylpentane', 'isooctane'), True, True),
    (('2,4-dimethylpentane',), True, True),
    (('2,4-dimethylpyridine',), True, True),
    (('2,6-dimethylpyridine',), True, True),
    (('2-bromopropane',), True, True),
    (('2-butanol', 'secbutanol'), True, True),
    (('2-chlorobutane',), True, True),
    (('2-heptanone',), True, True),
    (('2-hexanone',), True, True),
    (('2-methoxyethanol', 'methoxyethanol'), True, True),
    (('2-methyl-1-propanol', 'isobutanol'), True, True),
    (('2-methyl-2-propanol',), True, True),
    (('2-methylpentane',), True, True),
    (('2-methylpyridine', '2methylpyridine'), True, True),
    (('2-nitropropane',), True, True),
    (('2-octanone',), True, True),
    (('2-pentanone',), True, True),
    (('2-propanol', 'isopropanol'), True, True),
    (('2-propen-1-ol',), True, True),
    (('e-2-pentene',), True, True),
    (('3-methylpyridine',), True, True),
    (('3-pentanone',), True, True),
    (('4-heptanone',), True, True),
    (('4-methyl-2-pentanone', '4methyl2pentanone'), True, True),
    (('4-methylpyridine',), True, True),
    (('5-nonanone',), True, True),
    (('acetic acid', 'aceticacid'), True, True),
    (('acetone',), True, True),
    (('acetonitrile', 'mecn', 'ch3cn'), True, True),
    (('acetophenone',), True, True),
    (('ammonia',), True, False),
    (('aniline',), True, True),
    (('anisole',), True, True),
    (('benzaldehyde',), True, True),
    (('benzene',), True, True),
    (('benzonitrile',), True, True),
    (('benzyl alcohol', 'benzylalcohol'), True, True),
    (('bromobenzene',), True, True),
    (('bromoethane',), True, True),
    (('bromoform',), True, True),
    (('butanal',), True, True),
    (('butanoic acid',), True, True),
    (('butanone',), True, True),
    (('butanonitrile',), True, True),
    (('butyl ethanoate', 'butyl acetate', 'butylacetate'), True, True),
    (('butylamine',), True, True),
    (('n-butylbenzene', 'butylbenzene'), True, True),
    (('sec-butylbenzene', 'secbutylbenzene'), True, True),
    (('tert-butylbenzene', 'tbutylbenzene'), True, True),
    (('carbon disulfide', 'carbondisulfide', 'cs2'), True, True),
    (('carbon tetrachloride', 'ccl4'), True, True),
    (('chlorobenzene',), True, True),
    (('chloroform', 'chcl3'), True, True),
    (('a-chlorotoluene',), True, True),
    (('o-chlorotoluene',), True, True),
    (('conductor',), True, False),
    (('m-cresol', 'mcresol'), True, True),
    (('o-cresol',), True, True),
    (('cyclohexane',), True, True),
    (('cyclohexanone',), True, True),
    (('cyclopentane',), True, True),
    (('cyclopentanol',), True, True),
    (('cyclopentanone',), True, True),
    (('decalin',), True, True),
    (('cis-decalin',), True, True),
    (('n-decane', 'decane'), True, True),
    (('dibromomethane',), True, True),
    (('dibutylether',), True, True),
    (('o-dichlorobenzene', 'odichlorobenzene'), True, True),
    (('e-1,2-dichloroethene',), True, True),
    (('z-1,2-dichloroethene',), True, True),
    (('dichloromethane', 'ch2cl2', 'dcm'), True, True),
    (('diethyl ether', 'diethylether'), True, True),
    (('diethyl sulfide',), True, True),
    (('diethylamine',), True, True),
    (('diiodomethane',), True, True),
    (('diisopropyl ether', 'diisopropylether'), True, True),
    (('cis-1,2-dimethylcyclohexane',), True, True),
    (('dimethyl disulfide',), True, True),
    (('n,n-dimethylacetamide', 'dimethylacetamide'), True, True),
    (('n,n-dimethylformamide', 'dimethylformamide', 'dmf'), True, True),
    (('dimethylsulfoxide', 'dmso'), True, True),
    (('diphenylether',), True, True),
    (('dipropylamine',), True, True),
    (('n-dodecane', 'dodecane'), True, True),
    (('ethanethiol',), True, True),
    (('ethanol',), True, True),
    (('ethyl acetate', 'ethylacetate', 'ethanoate'), True, True),
    (('ethyl methanoate',), True, True),
    (('ethyl phenyl ether', 'ethoxybenzene'), True, True),
    (('ethylbenzene',), True, True),
    (('fluorobenzene',), True, True),
    (('formamide',), True, True),
    (('formic acid',), True, True),
    (('furan', 'furane'), False, False),
    (('n-heptane', 'heptane'), True, True),
    (('n-hexadecane', 'hexadecane'), True, True),
    (('n-hexane', 'hexane'), True, True),
    (('hexanoic acid',), True, True),
    (('iodobenzene',), True, True),
    (('iodoethane',), True, True),
    (('iodomethane',), True, True),
    (('isopropylbenzene',), True, True),
    (('p-isopropyltoluene', 'isopropyltoluene'), True, True),
    (('mesitylene',), True, True),
    (('methanol',), True, True),
    (('methyl benzoate',), True, True),
    (('methyl butanoate',), True, True),
    (('methyl ethanoate',), True, True),
    (('methyl methanoate',), True, True),
    (('methyl propanoate',), True, True),
    (('n-methylaniline',), True, True),
    (('methylcyclohexane',), True, True),
    (('n-methylformamide', 'methylformamide'), True, True),
    (('nitrobenzene', 'phno2'), True, True),
    (('nitroethane',), True, True),
    (('nitromethane', 'meno2'), True, True),
    (('o-nitrotoluene', 'onitrotoluene'), True, True),
    (('n-nonane', 'nonane'), True, True),
    (('n-octane', 'octane'), True, True),
    (('n-pentadecane', 'pentadecane'), True, True),
    (('octanol(wet)', 'wetoctanol', 'woctanol'), False, False),
    (('pentanal',), True, True),
    (('n-pentane', 'pentane'), True, True),
    (('pentanoic acid',), True, True),
    (('pentyl ethanoate',), True, True),
    (('pentylamine',), True, True),
    (('perfluorobenzene', 'hexafluorobenzene'), True, True),
    (('phenol',), True, False),
    (('propanal',), True, True),
    (('propanoic acid',), True, True),
    (('propanonitrile',), True, True),
    (('propyl ethanoate',), True, True),
    (('propylamine',), True, True),
    (('pyridine',), True, True),
    (('tetrachloroethene', 'c2cl4'), True, True),
    (('tetrahydrofuran', 'thf'), True, True),
    (('tetrahydrothiophene-s,s-dioxide', 'tetrahydrothiophenedioxide', 'sulfolane'), True, True),
    (('tetralin',), True, True),
    (('thiophene',), True, True),
    (('thiophenol',), True, True),
    (('toluene',), True, True),
    (('trans-decalin',), True, True),
    (('tributylphosphate',), True, True),
    (('trichloroethene',), True, True),
    (('triethylamine',), True, True),
    (('n-undecane', 'undecane'), True, True),
    (('water', 'h2o'), True, True),
    (('xylene',), True, True),
    (('m-xylene',), True, True),
    (('o-xylene',), True, True),
    (('p-xylene',), True, True),
)
