
from __future__ import annotations

from adit.errors import AditValueError
from pathlib import Path

from adit import handoff as hf
from adit.lang import L
from adit.spec import CalculationSpec, Handoff, Meta

MD = "molecular_dynamics"
MOVES = ("geometry_optimization", "molecular_dynamics")


class ContinuationError(AditValueError):
    pass


def _lammps_final(prev: CalculationSpec, d: Path) -> dict:
    from ase.data import atomic_numbers
    from ase.io.lammpsdata import read_lammps_data

    from adit.codes.lammps import type_elements

    p = d / "final.data"
    if not p.is_file():
        raise ContinuationError(L(f"{d} に final.data がありません (LAMMPS の最小化か MD が最後まで走ると write_data が書きます)",
                                  f"{d} has no final.data (written by write_data when a LAMMPS minimization or MD finishes)"))
    m = prev.method
    z = {i + 1: atomic_numbers[e] for i, e in enumerate(type_elements(prev))}
    a = read_lammps_data(str(p), Z_of_type=z, atom_style=m.atom_style.split()[0], units=m.units or "metal")
    return {"symbols": a.get_chemical_symbols(), "positions": a.get_positions().tolist(),
            "cell": a.cell.array.tolist() if any(prev.structure.atoms.pbc) else None, "velocities": None, "source": "final.data"}


def _gromacs_final(prev: CalculationSpec, d: Path) -> dict:
    from ase.io import read

    p = d / hf.existing_name(str(d), "{}.gro")
    if not p.is_file():
        raise ContinuationError(L(f"{d} に adit.gro がありません (gmx mdrun が最後まで走ると書きます)", f"{d} has no adit.gro (written when gmx mdrun finishes)"))
    a = read(str(p), format="gromacs")
    return {"symbols": None, "positions": a.get_positions().tolist(),
            "cell": a.cell.array.tolist() if any(prev.structure.atoms.pbc) else None, "velocities": None, "source": hf.existing_name(str(d), "{}.gro")}


def final_of(prev: CalculationSpec, d: Path) -> dict | None:
    code, task = prev.method.code, prev.task.type
    if task not in MOVES:
        return None
    try:
        if code == "lammps":
            return _lammps_final(prev, d)
        if code == "gromacs":
            return _gromacs_final(prev, d)
        return hf.final_structure(code, str(d), task)
    except FileNotFoundError as ex:
        raise ContinuationError(L(f"前の計算のディレクトリ {d} に {Path(ex.filename).name} がありません (計算が最後まで走ったか確かめてください)",
                                  f"{Path(ex.filename).name} is missing from the previous run {d} (check that it finished)")) from ex
    except (hf.HandoffError, ValueError, IndexError, StopIteration) as ex:
        raise ContinuationError(L(f"前の計算の最終構造を読めません ({d}): {ex}", f"cannot read the final structure of the previous run ({d}): {ex}")) from ex


def _in_spec_order(prev: CalculationSpec, fs: dict) -> tuple[list, list | None]:
    symbols = list(prev.structure.atoms.symbols)
    n = len(symbols)
    if len(fs["positions"]) != n:
        raise ContinuationError(L(f"前の計算の最終構造の原子数 ({len(fs['positions'])}) が spec.json の原子数 ({n}) と違います",
                                  f"the final structure has {len(fs['positions'])} atoms but spec.json has {n}"))
    if prev.method.code == "vasp":
        order = [i for e in prev.elements for i, s in enumerate(symbols) if s == e]
        pos, vel = [None] * n, ([None] * n if fs.get("velocities") else None)
        for k, i in enumerate(order):
            pos[i] = fs["positions"][k]
            if vel is not None:
                vel[i] = fs["velocities"][k]
        if fs.get("symbols") and [fs["symbols"][k] for k in range(n)] != [symbols[i] for i in order]:
            raise ContinuationError(L("CONTCAR の元素の並びが spec.json と合いません", "the element order of CONTCAR does not match spec.json"))
        return pos, vel
    if fs.get("symbols") and [s.capitalize() for s in fs["symbols"]] != [s.capitalize() for s in symbols]:
        raise ContinuationError(L(f"前の計算の最終構造 ({fs.get('source')}) の元素の並びが spec.json と合いません",
                                  f"the element order of the final structure ({fs.get('source')}) does not match spec.json"))
    return fs["positions"], fs.get("velocities")


def continue_from(prev_dir: Path | str, conditions: CalculationSpec | None = None, *, velocities: bool = True) -> CalculationSpec:
    import hashlib

    d = Path(prev_dir).expanduser().resolve()
    sp = d / "spec.json"
    if not sp.is_file():
        raise ContinuationError(L(f"{d} に spec.json がありません (ADIT が生成したディレクトリを指定してください)",
                                  f"{d} has no spec.json (give a directory generated by ADIT)"))
    prev = CalculationSpec.load(sp)
    base = conditions if conditions is not None else prev
    code, ptask = prev.method.code, prev.task.type
    new_task = base.task.type
    same = base.method.code == code
    want_vel = velocities and same and ptask == MD and new_task == MD
    fs = final_of(prev, d)
    carried, not_carried = [], []

    st = prev.structure.model_copy(deep=True)
    if fs is not None:
        pos, vel = _in_spec_order(prev, fs)
        atoms = st.atoms.model_copy(update={"positions": [tuple(float(x) for x in p) for p in pos]})
        if fs.get("cell") and any(st.atoms.pbc):
            atoms = atoms.model_copy(update={"cell": [tuple(float(x) for x in v) for v in fs["cell"]]})
            carried.append(L(f"位置とセル ({fs['source']} から)", f"positions and cell (from {fs['source']})"))
        else:
            carried.append(L(f"位置 ({fs['source']} から)", f"positions (from {fs['source']})"))
        st = st.model_copy(update={"atoms": atoms, "source": "file", "source_ref": str(d / fs["source"]), "velocities": None})
    else:
        carried.append(L("構造 (前の計算は構造を動かさない種類なので、前の入力の構造のまま)", "structure (the previous task does not move atoms, so the previous input structure)"))
        st = st.model_copy(update={"velocities": None})

    method = base.method.model_copy(deep=True)
    handoff = None
    if want_vel:
        if code in ("dftbplus", "vasp"):
            if fs is None or not fs.get("velocities"):
                raise ContinuationError(L(f"前の MD の出力 ({fs['source'] if fs else '?'}) に速度がありません", f"the previous MD output ({fs['source'] if fs else '?'}) has no velocities"))
            st = st.model_copy(update={"velocities": [tuple(float(x) for x in v) for v in vel]})
            carried.append(L("速度 (Å/fs に直して spec.json の structure.velocities に)", "velocities (converted to Å/fs, in structure.velocities of spec.json)"))
            if code == "vasp":
                not_carried.append(L("CONTCAR の予測子の欄と熱浴の状態 (ADIT は POSCAR を書き直すため)", "the predictor-corrector block and thermostat state of CONTCAR (ADIT rewrites POSCAR)"))
            handoff = Handoff(previous_dir=str(d), previous_task=ptask, previous_code=code, velocities=True)
        elif code == "xtb":
            if not (d / "mdrestart").is_file():
                raise ContinuationError(L(f"{d} に mdrestart がありません (xtb の MD が最後まで走ると書きます)", f"{d} has no mdrestart (written when the xtb MD finishes)"))
            handoff = Handoff(previous_dir=str(d), previous_task=ptask, previous_code=code, velocities=True, files={"mdrestart": "mdrestart"})
            carried.append(L("速度 (mdrestart を写し、$md restart=true)", "velocities (mdrestart copied, $md restart=true)"))
        elif code == "cp2k":
            if not fs or not fs.get("has_velocities"):
                name = hf.existing_name(str(d), "{}-1.restart")
                raise ContinuationError(L(f"{name} に &VELOCITY がありません", f"{name} has no &VELOCITY section"))
            handoff = Handoff(previous_dir=str(d), previous_task=ptask, previous_code=code, velocities=True, files={"prev.restart": hf.existing_name(str(d), "{}-1.restart")})
            carried.append(L("速度 (adit-1.restart を prev.restart に写し、&EXT_RESTART の RESTART_VEL)", "velocities (adit-1.restart copied to prev.restart; RESTART_VEL of &EXT_RESTART)"))
            not_carried.append(L("熱浴・圧力浴の状態 (新しい条件で始める)", "thermostat and barostat state (restarted with the new settings)"))
        elif code == "lammps":
            handoff = Handoff(previous_dir=str(d), previous_task=ptask, previous_code=code, velocities=True)
            carried.append(L("速度 (final.data の Velocities の節。velocity create をしない)", "velocities (the Velocities section of final.data; no velocity create)"))
        elif code == "gromacs":
            cpt = hf.existing_name(str(d), "{}.cpt")
            if not (d / cpt).is_file():
                raise ContinuationError(L(f"{d} に {cpt} がありません", f"{d} has no {cpt}"))
            method = method.model_copy(update={"checkpoint_file": str(d / cpt)})
            carried.append(L("速度と熱浴・圧力浴の状態 (adit.cpt を grompp -t に)", "velocities and thermostat/barostat state (adit.cpt to grompp -t)"))
        else:  # espresso, orca
            not_carried.append(L("速度 (この計算コードは出力に速度を書かないため。新しく初速を作ります)", "velocities (this code does not write them to its output; new initial velocities are generated)"))
    elif ptask == MD and new_task == MD and same:
        not_carried.append(L("速度 (引き継がない指定。新しく初速を作ります)", "velocities (not carried over by request; new initial velocities are generated)"))
    if same and code == "lammps" and ptask in MOVES:
        from adit.codes.lammps import type_elements
        method = method.model_copy(update={"data_file": str(d / "final.data"), "type_elements": type_elements(prev), "atom_style": prev.method.atom_style})
    if same and code == "gromacs" and ptask in MOVES:
        method = method.model_copy(update={"structure_file": str(d / hf.existing_name(str(d), "{}.gro"))})
        if not want_vel:
            method = method.model_copy(update={"checkpoint_file": ""})
    if not same:
        not_carried.append(L(f"続きの情報 (前の計算は {code}、今回は {base.method.code}。構造だけを使います)",
                             f"restart data (the previous run used {code}, this one {base.method.code}; only the structure is used)"))
    if handoff is None:
        handoff = Handoff(previous_dir=str(d), previous_task=ptask, previous_code=code)

    meta = Meta(comment=(base.meta.comment + f" continued from {d}").strip(), template=base.meta.template if conditions is not None else None,
                continued_from={"dir": str(d), "spec_sha256": hashlib.sha256(sp.read_bytes()).hexdigest(), "code": code, "task": ptask,
                                "structure_file": fs["source"] if fs else None, "velocities": bool(handoff.velocities),
                                "carried": carried, "not_carried": not_carried})
    data = base.model_dump(mode="json")
    data.update(meta=meta.model_dump(mode="json"), structure=st.model_dump(mode="json"), method=method.model_dump(mode="json"),
                handoff=handoff.model_dump(mode="json"))
    if not any(st.atoms.pbc):
        data["kpoints"] = None
    return CalculationSpec.model_validate(data)


__all__ = ["ContinuationError", "continue_from", "final_of"]
